HelpInfo,C:\Microchip\Libero_SoC_2025.2\Libero_SoC\Synplify_Pro\lib\html,fpgahelp.qhc,synerrmsg.mp,C:\Microchip\Libero_SoC_2025.2\Libero_SoC\Synplify_Pro\bin\assistant
Implementation;Place and Route;RootName:prj_2_memory_sb
Implementation;Place and Route||(null)||Please refer to the log file for details about 1 Warning(s) , 4 Info(s)||prj_2_memory_sb_layout_log.log;liberoaction://open_report/file/prj_2_memory_sb_layout_log.log||(null);(null)
